services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"

  bot:
    image: moltencore:latest
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    healthcheck:
      test: curl --fail http://localhost:8080/api/system/healthy || exit 1
      interval: 30s
      timeout: 2s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    container_name: moltencore
    volumes:
      - ./compose-alembic.ini:/usr/src/app/alembic.ini

volumes:
  db_data: {}
