[tool.poetry]
name = "modular"
version = "0.0.1alpha"
description = ""
authors = ["Stax124 <tamoncz@gmail.com>"]
license = "GPL-3"

[tool.poetry.dependencies]
python = "^3.10"
colored-logs = "^0.2.10"
discord-pretty-help = "^1.3.4"
DiscordUtils = "^1.3.4"
rich = "^12.4.4"
sqlmodel = "^0.0.6"
alembic = "^1.8.0"
coloredlogs = "^15.0.1"
discord = "^1.7.3"
psycopg2-binary = "^2.9.3"
requests = "^2.28.0"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
"discord.py-stubs" = "^1.7.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
docker = "scripts:docker"