name: black-action
on: [push, pull_request]
jobs:
  black-linter:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: datadog/action-py-black-formatter@v2.1
